name: Continuous Integration

on:
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Setup settings
        run: cp settings.ini.example settings.ini
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e py

  flake8:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Setup settings
        run: cp settings.ini.example settings.ini
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e pep8 py

  mypy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: ['3.9']

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install Tox
        run: pip install tox
      - name: Setup settings
        run: cp settings.ini.example settings.ini
      - name: Run Tox
        # Run tox using the version of Python in `PATH`
        run: tox -e mypy py